import { Router } from "express";
import Patient from "../models/Patient.js";
import { crudHandlers } from "./helpers.js";
const router = Router();
const h = crudHandlers(Patient);
router.get("/", h.list);
router.get("/:id", h.get);
router.post("/", h.create);
router.put("/:id", h.update);
router.delete("/:id", h.remove);
export default router;
